name: sound_speed
channels:
- conda-forge
dependencies:
- python=3.7.3
- pip>=8.1.0
- jupyter
- numpy=1.16.3
- pandas=0.24.2
- scikit-learn=0.20.3
- matplotlib=3.0.3
- pip:
  - git+https://github.com/scikit-optimize/scikit-optimize/
